[package]
name = "flxy_core"
version = "0.1.0"
authors = ["Jen-Chieh Shen <jcs090218@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
name = "flxy_core"
crate-type = ["cdylib"]

[dependencies]
emacs = "0.17"
flxy = "0.1.18"

[profile.release]
opt-level = 3
lto = "thin"
